[options]
addons_path = /mnt/tutorial-addons,/mnt/custom-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter = postgres2
list_db = True
workers = 0
log_level = info
